name: Update m3u

on:
  schedule:
#    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 Git 用户信息
      - name: Set Git user
        run: |
          git config --global user.email "congyong@163.com"
          git config --global user.name "cc"

      - name: Update ycl.m3u
        run: |
          # 下载远程文件
          wget "https://raw.githubusercontent.com/YueChan/Live/refs/heads/main/APTV.m3u" -O "IPTV.m3u"

          # 删除自第一个 group-title="国际" 到文件末尾的所有内容
          sed -i '/group-title="国际"/,$d' "IPTV.m3u"

          # 替换 group-title
          sed -i 's/group-title="[^"]*"/group-title="央视频道"/g' "IPTV.m3u"

          # 比较临时文件和 ycl.m3u
          if ! cmp -s "IPTV.m3u" "ycl.m3u"; then
              # 覆盖 ycl.m3u
              cp "IPTV.m3u" "ycl.m3u"

              # 提交更改到 Git
              git add "ycl.m3u"
              git commit -m "Update group-title to 央视频道 in ycl.m3u"
              git push
          fi

      - name: Update fmml.m3u
        run: |
          # 下载远程文件
          # wget "https://raw.githubusercontent.com/fanmingming/live/refs/heads/main/tv/m3u/ipv6.m3u" -O "ipv6Plus.m3u"
          wget "https://raw.githubusercontent.com/fanmingming/live/main/tv/m3u/ipv6.m3u" -O "ipv6Plus.m3u"

          # 替换 group-title
          sed -i 's/group-title="[^"]*"/group-title="央视频道"/g' "ipv6Plus.m3u"

          # 比较临时文件和 fmml.m3u
          if ! cmp -s "ipv6Plus.m3u" "fmml.m3u"; then
              # 覆盖 fmml.m3u
              cp "ipv6Plus.m3u" "fmml.m3u"

              # 提交更改到 Git
              git add "fmml.m3u"
              git commit -m "Update group-title to 央视频道 in fmml.m3u"
              git push
          fi

      - name: Update kilvn.m3u
        run: |
          # 下载远程文件
          wget "https://raw.githubusercontent.com/kilvn/iptv/refs/heads/master/iptv.m3u" -O "ktmp.m3u"

          # 替换 group-title
          sed -i 's/group-title="卫视频道"/group-title="央视频道"/g' "ktmp.m3u"

          # 比较临时文件和 fmml.m3u
          if ! cmp -s "ktmp.m3u" "kilvn.m3u"; then
              # 覆盖 fmml.m3u
              cp "ktmp.m3u" "kilvn.m3u"

              # 提交更改到 Git
              git add "kilvn.m3u"
              git commit -m "Update group-title to 央视频道 in kilvn.m3u"
              git push
          fi


      - name: Update Gather.m3u
        run: |
            wget "https://raw.githubusercontent.com/YanG-1989/m3u/refs/heads/main/Gather.m3u" -O "temp_Gather.m3u"
            sed -i 's/group-title=".*IPV6.*"/group-title="我的IPV6"/' "temp_Gather.m3u"
            if [ -f "Gather_mg.m3u" ]; then
               if ! cmp -s "temp_Gather.m3u" "Gather_mg.m3u"; then
                cp "temp_Gather.m3u" "Gather_mg.m3u"
                git add "Gather_mg.m3u"
                git commit -m "Update Gather_mg.m3u"
                git push
              fi
            else
              cp "temp_Gather.m3u" "Gather_mg.m3u"
              git add "Gather_mg.m3u"
              git commit -m "Create Gather_mg.m3u"
              git push
            fi
          
      - name: Pull and Push Original Gather.m3u
        run: |
          wget https://raw.githubusercontent.com/YanG-1989/m3u/refs/heads/main/Gather.m3u -O "local_Gather.m3u"
          if ! cmp -s "local_Gather.m3u" "Gather.m3u"; then
            cp "local_Gather.m3u" "Gather.m3u"
            git add "Gather.m3u"
            git commit -m "Pull and update original Gather.m3u"
            git push
          fi


      - name: Update yuanzl77 live.m3u
        run: |
          wget "https://raw.githubusercontent.com/yuanzl77/IPTV/refs/heads/main/live.m3u" -O "temp_yuanzl77.m3u"
          sed -i '/group-title="公告"/,+1d' "temp_yuanzl77.m3u"
          sed -i 's/group-title="[^"]*"/group-title="IPTV"/g' "temp_yuanzl77.m3u"
          if [ -f "yuanzl77.m3u" ]; then
            if ! cmp -s "temp_yuanzl77.m3u" "yuanzl77.m3u"; then
              cp "temp_yuanzl77.m3u" "yuanzl77.m3u"
              git add "yuanzl77.m3u"
              git commit -m "Update yuanzl77.m3u"
              git push
            fi
          else
            cp "temp_yuanzl77.m3u" "yuanzl77.m3u"
            git add "yuanzl77.m3u"
            git commit -m "Create yuanzl77.m3u"
            git push
          fi
  

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
