name: Sync to Gitee
on: [ push, delete, create ]
jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Git
        run: |
          git config --global user.name 'mars' 
          git config --global user.email '14350252+marspiapia@user.noreply.gitee.com'
      - name: Add Gitee remote
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          #git remote add gitee https://${{ secrets.GITEE_TOKEN }}@gitee.com/marspiapia/my_ipv6.git
          # 下面这句替换原来的git remote add gitee 语句
           git remote add gitee https://marspiapia:${{ secrets.GITEE_TOKEN }}@gitee.com/marspiapia/my_ipv6.git
      - name: Push to Gitee
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git push -u gitee main:main --force
